name: Build and Deploy

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '18.x.x'

    - name: Build
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
        npm install --openssl-legacy-provider
        npm run build --openssl-legacy-provider 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_dir: ./build
