name: Build and Deploy # adding a comment to rebuild -- it should work now since i renamed it from dark-scratch to scratch-gui

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Build and Deploy
      run: |
        cd ../
        npm run build
        npm run deploy
