name: Build and Deploy

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x.x'

    - name: Build and Deploy
      run: |
        npm install -g pnpm
        pnpm install
        pnpm build
        pnpm deploy
